#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp.

# Check if all 4 parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
file_path=$1
ip_address=$2
username=$3
ssh_key_path=$4

# Transfer the file using scp
scp -i "$ssh_key_path" -o StrictHostKeyChecking=no "$file_path" "$username"@"$ip_address":~/
