#!/usr/bin/env bash
# This script installs nginx web server on an Ubuntu machine.

# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Check if nginx is installed and running
if systemctl is-active --quiet nginx; then
    echo "Nginx installed and running."
else
    echo "Error: Nginx installation or startup failed."
fi
