#!/usr/bin/env bash
# This script configures Nginx for a 301 redirect.

# Create a custom configuration file
echo "location /redirect_me {" > /etc/nginx/sites-available/redirect_me
echo "    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" >> /etc/nginx/sites-available/redirect_me
echo "}" >> /etc/nginx/sites-available/redirect_me

# Link the configuration file
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart nginx
service nginx restart
