#!/usr/bin/env bash
# This script configures Nginx to have a custom 404 page.

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Update Nginx configuration to use the custom 404 page
echo "error_page 404 /404.html;" | sudo tee -a /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo nginx -s reload

echo "Custom 404 page configured successfully."
