#!/usr/bin/env bash
# This script configures Nginx for a custom 404 page.

# Create a custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404 page
echo "error_page 404 /404.html;" >> /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
