#!/usr/bin/env bash
# This script configures Nginx to listen on port 80.

# Update Nginx configuration to listen on port 80
sed -i 's/listen\s*\(.*\);/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
