#!/bin/env bash

# Start the 4-to_infinity_and_beyond process in the background
./4-to_infinity_and_beyond &

# Capture the PID of the background process
PID=$!

# Wait for a moment to let the process start running
sleep 2

# Stop the 4-to_infinity_and_beyond process using kill
kill $PID

# Print a message to indicate that the process has been terminated
echo "Terminated"
