#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond script
PID=$(pgrep -o "4-to_infinity_and_beyond")

# If the process is not running, exit the script
if [[ -z "$PID" ]]; then
  echo "The 4-to_infinity_and_beyond process is not running."
  exit 1
fi

# Stop the process group, which includes the 4-to_infinity_and_beyond process
pkill -P "$PID"

echo "Terminated"
