#!/usr/bin/env bash
# This script stops the 7-highlander process by sending the SIGTERM signal.

# Find the PID of the 7-highlander process
PID=$(pgrep -o "7-highlander")

# If the process is not running, exit the script
if [[ -z "$PID" ]]; then
  echo "The 7-highlander process is not running."
  exit 1
fi

# Stop the process by sending the SIGTERM signal
kill -SIGTERM "7-hihlander"

echo "Terminated"
