#!/usr/bin/env bash
# This script reads and displays the content of /etc/passwd showing username, user ID, and home directory path

while IFS=':' read -r username _ userid _ homedir _; do
    echo "$username:$userid:$homedir"
done < /etc/passwd
