#!/usr/bin/env bash
# A Bash script that accepts one argument
# The script run the 'whoami' command under the user passed as an argument

# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

# Run 'whoami' command under the provided user
sudo -u "$1" whoami
