#!/usr/bin/env bash
# This script configures Nginx to run as the less privileged nginx user.

# Update Nginx configuration to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Reload Nginx for changes to take effect
service nginx reload
