#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
# Update Nginx configuration to run as nginx user
sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
# Reload Nginx for changes to take effect
service nginx reload
